name: generete readme

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: generate readme
        uses: plzprayme/online-judge-directory-tree-to-readme@beta
