name: generete readme

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: readme
        uses: plzprayme/online-judge-directory-tree-to-readme@beta
      
      
      - name: print outs
        run: |
          echo "The time was ${{ steps.readme.outputs.list }}"
          echo "The time was ${{ steps.readme.outputs.cur }}"
          echo "The time was ${{ steps.readme.outputs.result }}"
          echo "The time was ${{ steps.readme.outputs.list2 }}"
